# Generated by Django 4.1.4 on 2022-12-26 18:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='nomi')),
                ('slug', models.SlugField(max_length=128, verbose_name='slug')),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('is_active', models.BooleanField(default=False)),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Todo', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('measure', models.CharField(choices=[('metr', 'Metrida'), ('weight', "o'girligida"), ('number', 'sonida')], max_length=256)),
                ('quantity', models.PositiveIntegerField()),
                ('buy', models.PositiveIntegerField()),
                ('sell', models.PositiveIntegerField()),
                ('comment', models.TextField(blank=True)),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group', to='main.group')),
            ],
        ),
        migrations.CreateModel(
            name='MontylyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income', models.PositiveIntegerField(verbose_name='kirim')),
                ('outcome', models.PositiveIntegerField(verbose_name='chiqim')),
                ('sells', models.PositiveIntegerField(verbose_name='sotildi')),
                ('buy', models.PositiveIntegerField(verbose_name='sotib olindi')),
                ('end_date', models.DateField(blank=True, default=main.models.one_month_from_today, null=True)),
                ('factory', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='HistoryProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.CharField(blank=True, max_length=256)),
                ('is_calc', models.BooleanField(default=True)),
                ('comment', models.TextField(blank=True)),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='main.product')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
