# Generated by Django 4.1.4 on 2022-12-27 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historyproduct',
            name='mode',
            field=models.CharField(choices=[("qo'shish", 'add'), ('sotish', 'remove')], max_length=256),
        ),
        migrations.AlterField(
            model_name='product',
            name='measure',
            field=models.CharField(choices=[('Metrida', 'metr'), ("o'girligida", 'weight'), ('sonida', 'number')], max_length=256),
        ),
    ]
