# Generated by Django 4.1.4 on 2022-12-27 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_historyproduct_mode_alter_product_measure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historyproduct',
            name='mode',
            field=models.IntegerField(choices=[(0, 'add'), (1, 'remove')], max_length=256),
        ),
    ]
