# Generated by Django 4.1.4 on 2022-12-27 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_historyproduct_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historyproduct',
            name='mode',
            field=models.IntegerField(choices=[(0, "qo'shish"), (1, 'Sotish')], max_length=256),
        ),
    ]
