# Generated by Django 4.1.4 on 2023-01-06 06:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_product_measure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='comment',
        ),
        migrations.AddField(
            model_name='cart',
            name='customer_adress',
            field=models.CharField(default=django.utils.timezone.now, max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cart',
            name='customer_name',
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cart',
            name='customer_number',
            field=models.CharField(default=django.utils.timezone.now, max_length=256),
            preserve_default=False,
        ),
    ]
