# Generated by Django 4.1.4 on 2023-01-06 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_cart_comment_cart_customer_adress_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='customer_adress',
            new_name='adress',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='customer_name',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='customer_number',
            new_name='number',
        ),
    ]
