# Generated by Django 4.1.4 on 2022-12-28 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_historyproduct_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historyproduct',
            name='mode',
            field=models.CharField(choices=[('add', "qo'shish"), ('sale', 'Sotish')], max_length=128),
        ),
    ]
