# Generated by Django 4.1.4 on 2022-12-28 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_historyproduct_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historyproduct',
            name='created_at',
            field=models.DateTimeField(verbose_name='Yaratildi'),
        ),
    ]
