# Generated by Django 4.1.4 on 2022-12-28 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_historyproduct_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historyproduct',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
    ]
