# Generated by Django 4.1.4 on 2022-12-29 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_product_measure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historyproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', related_query_name='tag', to='main.product'),
        ),
    ]
