# Generated by Django 4.1.4 on 2023-01-05 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_product_measure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='measure',
            field=models.CharField(choices=[('Metr', 'metr'), ('kg', 'kg'), ('sonida', 'number')], max_length=256),
        ),
    ]
